### ISSUE TITLE
listDatabases not implemented

### ISSUE THREAD

**Issue by jondoveston** [gdb/embedded-mongo#6]
Thanks for your hard work.

Are you intending to implement the connection.database_info method.

NotImplementedError: Unrecognized command {"listDatabases"=>1}

**Comment by gdb** [comment]
I'm not currently actively developing EmbeddedMongo. (Full-time job and all that.) I am however accepting pull-requests, and some members of the community have been awesome enough to contribute patches in the past. If you're interested in doing some development, I'd be happy to review/merge your changes.
